### ISSUE TITLE
mutate_if.data.frame calls as.data.frame instead of as.data.table

### ISSUE THREAD

**Issue by blasern** [skranz/dplyrExtras#4]
The current version of `mutate_if.data.frame` seems to call `as.data.frame` in the first line. I think it should be `as.data.table`. Because later you call `mutate_if.data.table` on the newly created `dt`. 

    mutate_if.data.frame =function (.data,.if,...)
    {
      dt = as.data.table(.data) # changed from dt = as.data.frame(.data)
      .if.quoted = substitute(.if)
      as.data.frame(mutate_if.data.table(.data=dt,.if.quoted=.if.quoted,...,inplace=TRUE, .parent.env = parent.frame()))
    }

**Comment by skranz** [comment]
Thanks a lot. 

Somehow this change slipped in when making this commit:
https://github.com/skranz/dplyrExtras/commit/6e6ef4128249e4babbb7a01db9f8022b418c3b42

To be on the safe side (see disussion here https://github.com/hadley/dplyr/issues/425#issuecomment-75378972) I changed the code to:
```r
dt = as.data.table(as.data.frame(.data))
```
The new version is on github.
