### ISSUE TITLE
Feature rejected by hadley: add variable labels to the tbl_df class

### ISSUE THREAD

**Issue by kendonB** [skranz/dplyrExtras#6]
The original issue is here: https://github.com/hadley/dplyr/issues/1307

Variable labels are one of the few remaining features that are nicer in Stata. These are used for variable descriptions that are longer than appropriate for a title.

The call would be something like:

    my_tbl_df %>% select(my_var_1, my_var_2) %>% labels()

And the output would be a character vector of the variable labels for ``my_var_1`` and ``my_var_2``.

Might be a good addition to dplyrExtras!

**Comment by skranz** [comment]
I don't think that is very easy to implement in a sensible fashion. While you could store the labels as an attribute, you need to make sure that they survive the various dplyr operations. Also once you load or save from a csv file, the labels would vanish.

That being said, the read.dat function in the foreign package allows Stata files with labels to be loaded. If you like, you can check out whether these labels survive all common dplyr operations. Then writing a `labels` functions should be straightforward. If you like, you can try to implement it in an own small package, and if it works fine, and we think it makes sense, we can merge it to dplyrExtras.
