### ISSUE TITLE
group_by doesn't work nicely with mutate_if

### ISSUE THREAD

**Issue by kendonB** [skranz/dplyrExtras#8]
iris %>% group_by(Species) %>% mutate_if(Sepal.Length > mean(Sepal.Length), Sepal.Length = 5)
    Error: object 'INDEX.ROW__' not found

**Comment by skranz** [comment]
Thanks for the info. I don't know why it stopped working. I changed one line of the code and uploaded the new version. It should work again...

**Comment by tiernanmartin** [comment]
'mutate_rows' is experiencing a similar failure:

iris %>% group_by(Species) %>% mutate_rows(Sepal.Length > mean(Sepal.Length), Sepal.Length = 5)
`Error in select(arrange(data, INDEX.ROW__), -INDEX.ROW__) :  unused argument (-INDEX.ROW__)`

**Comment by skranz** [comment]
Strange, your example works fine without error on my computer... I have no clue, why you get the error. Can you show a traceback? Could it be that you load another package with a select function which is used instead of dplyr select?

**Comment by tiernanmartin** [comment]
@skranz : your instinct was correct – it works fine when `dplyr::select` isn't masked (careless on my part). 

Thanks!
