### ISSUE TITLE
mutate_rows no longer working (breaking change in dplyr 0.7.0?)

### ISSUE THREAD

**Issue by EllaKaye** [skranz/dplyrExtras#9]
Hello. I use mutate_rows a lot and I just started getting an error message on code that used to work fine, which I suspect has something to do with the update to dplyr 0.7.0.

For example, the code 
```r
library(dplyr)
library(dplyrExtras)
df <- tibble(a = c(1,2,1), b = letters[2:4])
df %>% mutate_rows(a == 1, b = "hello")
```

leads to the following error message `Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'named_dots' not found'`

Since `named_dots` is a dplyr function, I'm guessing that's where the issue is. Is there a fix that you can implement in dplyrExtras to get around whatever was changed in the dplyr update?

**Comment by skranz** [comment]
Thanks for the report. I uploaded a new version that should fix the problem. (I have not yet extensively tested it, but your example works.).
BTW: I guess for new projects, there are now good replacements for `mutate_rows` via the new dplyr functions `case_when` and `recode`. But of course it is nice if `mutate_rows` remains working.

**Comment by EllaKaye** [comment]
Thanks for getting on that so quickly. The fix is now working fine on my old code. `case_when` and `recode` have been around since `dplyr 0.5.0`, but I still find the syntax of `mutate_rows` more convenient/intuitive when the cases aren't that complex. Thanks for keeping it up!
